/* This file was automatically generated by the make-infomodel script
 * using the "*.xml" files in the ../infomodel directory.
 */

#ifndef _GUARD_INFOMODEL_H
#define _GUARD_INFOMODEL_H

#include <fixbuf/public.h>

/**
 *    Updates the information model 'model' with the elements defined
 *    in the *.i files, created from the corresponding *.xml files.
 */
#define infomodelAddGlobalElements infomodelAddGlobalElements_yaf
void infomodelAddGlobalElements(fbInfoModel_t *model);

/**
 *    Returns a handle to the information element array defined in the
 *    file whose name is '<name>.i', created from '<name>.xml'.
 *    Returns NULL if 'name' is NULL or does not name a known file.
 */
#define infomodelGetArrayByName infomodelGetArrayByName_yaf
const fbInfoElement_t *infomodelGetArrayByName(const char *name);

/**
 *    Returns the number of elements (including the final FB_IE_NULL)
 *    in the information element array defined in the file whose name
 *    is '<name>.i', created from '<name>.xml'.  Returns 0 if 'name'
 *    is NULL or does not name a known file.
 */
#define infomodelGetArrayLengthByName infomodelGetArrayLengthByName_yaf
size_t infomodelGetArrayLengthByName(const char *name);

#endif  /* _GUARD_INFOMODEL_H */

/*
** Local Variables:
** mode:c
** indent-tabs-mode:nil
** c-basic-offset:4
** End:
*/
